# Generated by Django 3.0.3 on 2020-02-12 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Distância em km')),
                ('date', models.DateField(help_text='No formato dd/mm/aaaa', verbose_name='Data')),
                ('slug', models.SlugField(help_text='Preenchido automaticamente, não editar.', max_length=100, verbose_name='Identificador')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'ordering': ['created'],
            },
        ),
    ]
